#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/bin/nxgit"
daemon_user="git"
daemon_flags="web -c /etc/nxgit/app.ini"

nxgit_directory="/var/lib/nxgit"

rc_bg=YES

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "cd ${nxgit_directory}; ${daemon} ${daemon_flags} ${_bg}"
}

rc_cmd $1
