#!/bin/sh
#
#       /etc/rc.d/init.d/nxgit
#
#       Runs the Nxgit Git with a cup of tea.
#
#
# chkconfig:   - 85 15
#

### BEGIN INIT INFO
# Provides:          nxgit
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start nxgit at boot time.
# Description:       Control nxgit.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Default values

NAME=nxgit
NXGIT_HOME=/var/lib/${NAME}
NXGIT_PATH=/usr/local/bin/${NAME}
NXGIT_USER=git
SERVICENAME="Nxgit - Git with a cup of tea"
LOCKFILE=/var/lock/subsys/nxgit
LOGPATH=${NXGIT_HOME}/log
LOGFILE=${LOGPATH}/nxgit.log
RETVAL=0

# Read configuration from /etc/sysconfig/nxgit to override defaults
[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

# Don't do anything if nothing is installed
[ -x ${NXGIT_PATH} ] || exit 0
# exit if logpath dir is not created.
[ -x ${LOGPATH} ] || exit 0

DAEMON_OPTS="--check $NAME"

# Set additional options, if any
[ ! -z "$NXGIT_USER" ] && DAEMON_OPTS="$DAEMON_OPTS --user=${NXGIT_USER}"

start() {
  cd ${NXGIT_HOME}
  echo -n "Starting ${SERVICENAME}: "
  daemon $DAEMON_OPTS "${NXGIT_PATH} web -c /etc/${NAME}/app.ini > ${LOGFILE} 2>&1 &"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch ${LOCKFILE}

  return $RETVAL
}

stop() {
  cd ${NXGIT_HOME}
        echo -n "Shutting down ${SERVICENAME}: "
        killproc ${NAME}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${LOCKFILE}
}

case "$1" in
    start)
        status ${NAME} > /dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${NAME}
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
